import type { Metadata } from 'next';
// Removed font imports from next/font/google
import './globals.css';
import { EntriesProvider } from '@/context/EntriesContext';

// Removed font instantiations

export const metadata: Metadata = {
  title: "Clarity",
  description: "ADHD Planning Tool PoC",
  icons: {
    icon: [
      { url: '/favicons/favicon.ico', sizes: 'any' },
      { url: '/favicons/favicon-16x16.png', type: 'image/png', sizes: '16x16' },
      { url: '/favicons/favicon-32x32.png', type: 'image/png', sizes: '32x32' },
    ],
    apple: [
      { url: '/favicons/apple-touch-icon.png', type: 'image/png' },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Reverted className, removed font variables
    <html lang="en">
      <head>
        {/* Favicon links generated by Next.js metadata are automatically added here */}
        {/* Re-add Google Font links */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet" />
      </head>
      <body suppressHydrationWarning className="bg-white text-black">
        <EntriesProvider>{children}</EntriesProvider>
      </body>
    </html>
  );
}
